apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mywebapp-ingress
  namespace: dev
  annotations:
    # cert-manager.io/issuer: "devtest-letsencrypt-prod"
  # spec:
  #   tls:
  #     - hosts:
  #         - $(hostname)
  #       secretName: mywebapp-tls-secret
  rules:
    - host: $(hostname)
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kustom-mywebapp-v1
                port:
                  number: 80
