apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mywebapp-ingress
  namespace: dev
  annotations:
    # cert-manager.io/issuer: "devtest-letsencrypt-prod"
  # spec:
  #   tls:
  #   - hosts:
  #     - <YOUR_HOSTNAME>
  #     secretName: mywebapp-tls-secret
  rules:
    - host: argotest.wannes.stages-2024.axxes.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kustom-mywebapp-v1
                port:
                  number: 80
