resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app: kustomwebapp

commonAnnotations:
  app: mykustom-annontations

namePrefix: kustom-

nameSuffix: -v1
# configMapGenerator:
#   - name: hostname-configmap
#     literals:
#       - hostname=argotest.wannes.stages-2024.axxes.cloud
