kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ .Values.configmap.name }}
data:
  BG_COLOR: {{ .Values.configmap.data.BG_COLOR }}
  FONT_COLOR: '#FFFFFF'
  CUSTOM_HEADER: {{ .Values.configmap.data.CUSTOM_HEADER }}